## HW 2

In [2]:
import pandas as pd

# TODO: Load up the 'tutorial.csv' dataset
#
# .. your code here ..
census = pd.read_csv('datasets/tutorial.csv')


# TODO: Print the results of the .describe() method
#
# .. your code here ..
print(census.describe())


# TODO: Figure out which indexing method you need to
# use in order to index your dataframe with: [2:4,'col3']
# And print the results
#
# .. your code here ..

print(census.loc[2:4, 'col3'])

           col0      col1      col2      col3
count  4.000000  4.000000  4.000000  4.000000
mean  -0.047068 -0.550656  0.409203 -0.447672
std    1.029715  0.701720  0.723956  1.300815
min   -1.062870 -1.330682 -0.238536 -1.649853
25%   -0.807875 -0.880830 -0.143055 -1.475916
50%   -0.142899 -0.617291  0.283070 -0.592780
75%    0.617907 -0.287118  0.835328  0.435464
max    1.160396  0.362640  1.309208  1.044722
2   -1.417937
3   -1.649853
Name: col3, dtype: float64

## HW 3

In [3]:
import pandas as pd

# TODO: Load up the dataset
# Ensuring you set the appropriate header column names
#
# .. your code here ..
hds = ['motor', 'screw', 'pgain', 'vgain', 'class']
df = pd.read_csv('datasets/servo.data', names=hds)
print(df.head(5))
# TODO: Create a slice that contains all entries
# having a vgain equal to 5. Then print the 
# length of (# of samples in) that slice:
#
# .. your code here ..
vslice = df[df['vgain']==5]
print(vslice.describe())
# TODO: Create a slice that contains all entries
# having a motor equal to E and screw equal
# to E. Then print the length of (# of
# samples in) that slice:
#
# .. your code here ..
mslice = df[(df['motor']=='E') & (df['screw']=='E')]
print(mslice.describe())


# TODO: Create a slice that contains all entries
# having a pgain equal to 4. Use one of the
# various methods of finding the mean vgain
# value for the samples in that slice. Once
# you've found it, print it:
#
# .. your code here ..
pslice = df[df['pgain']==4]
print(pslice.describe())


# TODO: (Bonus) See what happens when you run
# the .dtypes method on your dataframe!
print(df.dtypes)

  motor screw  pgain  vgain     class
0     E     E      5      4  0.281251
1     B     D      6      5  0.506252
2     D     D      4      3  0.356251
3     B     A      3      2  5.500033
4     D     B      6      5  0.356251
       pgain  vgain      class
count   22.0   22.0  22.000000
mean     6.0    5.0   0.511366
std      0.0    0.0   0.138050
min      6.0    5.0   0.281251
25%      6.0    5.0   0.440627
50%      6.0    5.0   0.506252
75%      6.0    5.0   0.543753
max      6.0    5.0   0.806255
          pgain     vgain     class
count  6.000000  6.000000  6.000000
mean   4.166667  2.833333  0.618752
std    1.169045  1.471960  0.325361
min    3.000000  1.000000  0.281251
25%    3.250000  2.000000  0.337501
50%    4.000000  2.500000  0.603127
75%    4.750000  3.750000  0.807816
max    6.000000  5.000000  1.100000
       pgain      vgain      class
count   66.0  66.000000  66.000000
mean     4.0   2.060606   0.673298
std      0.0   0.820484   0.314105
min      4.0   1.000000   0.131250
25%      4.0   1.000000   0.365627
50%      4.0   2.000000   0.712504
75%      4.0   3.000000   0.956256
max      4.0   3.000000   1.218740
motor     object
screw     object
pgain      int64
vgain      int64
class    float64
dtype: object

## HW 4

In [31]:
import pandas as pd


# TODO: Load up the table, and extract the dataset
# out of it. If you're having issues with this, look
# carefully at the sample code provided in the reading
#
# .. your code here ..
df = pd.read_html('http://www.espn.com/nhl/statistics/player/_/stat/points/sort/points/year/2015/seasontype/2', header=1)
df = df[0]
print(df.describe())
# TODO: Rename the columns so that they match the
# column definitions provided to you on the website
#
# .. your code here ..

# did it iwth header = 1 bishes 
print(df.shape)

        RK  PLAYER TEAM  GP   G   A PTS +/- PIM PTS/G  SOG  PCT GWG G.1 A.1  \
count   21      46   46  43  43  43  43  43  43    43   43   43  43  43  43
unique  19      42   23  13  21  24  19  27  29    28   40   37  11  16  21
top     RK  PLAYER   TB  82  28  40  64   5  36  0.80  SOG  PCT   6   6  18
freq     3       3    4  14   5   5   7   5   4     4    3    3   8   9   4

       G.2 A.2
count   43  43
unique   6   5
top      0   0
freq    31  32
(46, 17)

In [32]:

# TODO: Get rid of any row that has at least 4 NANs in it
#
# .. your code here ..
df = df.dropna(axis=0, thresh=(17-4))
print(df.describe())
print(df.shape)
print(df)

        RK  PLAYER TEAM  GP   G   A PTS +/- PIM PTS/G  SOG  PCT GWG G.1 A.1  \
count   21      43   43  43  43  43  43  43  43    43   43   43  43  43  43
unique  19      41   22  13  21  24  19  27  29    28   40   37  11  16  21
top     RK  PLAYER   TB  82  28  40  64   5  36  0.80  SOG  PCT   6   6  18
freq     3       3    4  14   5   5   7   5   4     4    3    3   8   9   4

       G.2 A.2
count   43  43
unique   6   5
top      0   0
freq    31  32
(43, 17)
     RK                  PLAYER  TEAM  GP   G   A  PTS  +/-  PIM  PTS/G  SOG  \
0     1          Jamie Benn, LW   DAL  82  35  52   87    1   64   1.06  253
1     2         John Tavares, C   NYI  82  38  48   86    5   46   1.05  278
2     3        Sidney Crosby, C   PIT  77  28  56   84    5   47   1.09  237
3     4       Alex Ovechkin, LW   WSH  81  53  28   81   10   58   1.00  395
4   NaN       Jakub Voracek, RW   PHI  82  22  59   81    1   78   0.99  221
5     6    Nicklas Backstrom, C   WSH  82  18  60   78    5   40   0.95  153
6     7         Tyler Seguin, C   DAL  71  37  40   77   -1   20   1.08  280
7     8         Jiri Hudler, LW   CGY  78  31  45   76   17   14   0.97  158
8   NaN        Daniel Sedin, LW   VAN  82  20  56   76    5   18   0.93  226
9    10  Vladimir Tarasenko, RW   STL  77  37  36   73   27   31   0.95  264
11   RK                  PLAYER  TEAM  GP   G   A  PTS  +/-  PIM  PTS/G  SOG
12  NaN        Nick Foligno, LW   CBJ  79  31  42   73   16   50   0.92  182
13  NaN        Claude Giroux, C   PHI  81  25  48   73   -3   36   0.90  279
14  NaN         Henrik Sedin, C   VAN  82  18  55   73   11   22   0.89  101
15   14       Steven Stamkos, C    TB  82  43  29   72    2   49   0.88  268
16  NaN        Tyler Johnson, C    TB  77  29  43   72   33   24   0.94  203
17   16        Ryan Johansen, C   CBJ  82  26  45   71   -6   40   0.87  202
18   17         Joe Pavelski, C    SJ  82  37  33   70   12   29   0.85  261
19  NaN        Evgeni Malkin, C   PIT  69  28  42   70   -2   60   1.01  212
20  NaN         Ryan Getzlaf, C   ANA  77  25  45   70   15   62   0.91  191
21   20           Rick Nash, LW   NYR  79  42  27   69   29   36   0.87  304
23   RK                  PLAYER  TEAM  GP   G   A  PTS  +/-  PIM  PTS/G  SOG
24   21      Max Pacioretty, LW   MTL  80  37  30   67   38   32   0.84  302
25  NaN        Logan Couture, C    SJ  82  27  40   67   -6   12   0.82  263
26   23       Jonathan Toews, C   CHI  81  28  38   66   30   36   0.81  192
27  NaN        Erik Karlsson, D   OTT  82  21  45   66    7   42   0.80  292
28  NaN   Henrik Zetterberg, LW   DET  77  17  49   66   -6   32   0.86  227
29   26        Pavel Datsyuk, C   DET  63  26  39   65   12    8   1.03  165
30  NaN         Joe Thornton, C    SJ  78  16  49   65   -4   30   0.83  131
31   28     Nikita Kucherov, RW    TB  82  28  36   64   38   37   0.78  190
32  NaN        Patrick Kane, RW   CHI  61  27  37   64   10   10   1.05  186
33  NaN          Mark Stone, RW   OTT  80  26  38   64   21   14   0.80  157
35   RK                  PLAYER  TEAM  GP   G   A  PTS  +/-  PIM  PTS/G  SOG
36  NaN     Alexander Steen, LW   STL  74  24  40   64    8   33   0.86  223
37  NaN          Kyle Turris, C   OTT  82  24  40   64    5   36   0.78  215
38  NaN     Johnny Gaudreau, LW   CGY  80  24  40   64   11   14   0.80  167
39  NaN         Anze Kopitar, C    LA  79  16  48   64   -2   10   0.81  134
40   35        Radim Vrbata, RW   VAN  79  31  32   63    6   20   0.80  267
41  NaN      Jaden Schwartz, LW   STL  75  28  35   63   13   16   0.84  184
42  NaN       Filip Forsberg, C   NSH  82  26  37   63   15   24   0.77  237
43  NaN       Jordan Eberle, RW   EDM  81  24  39   63  -16   24   0.78  183
44  NaN        Ondrej Palat, LW    TB  75  16  47   63   31   24   0.84  139
45   40         Zach Parise, LW   MIN  74  33  29   62   21   41   0.84  259

     PCT  GWG G.1 A.1 G.2 A.2
0   13.8    6  10  13   2   3
1   13.7    8  13  18   0   1
2   11.8    3  10  21   0   0
3   13.4   11  25   9   0   0
4   10.0    3  11  22   0   0
5   11.8    3   3  30   0   0
6   13.2    5  13  16   0   0
7   19.6    5   6  10   0   0
8    8.9    5   4  21   0   0
9   14.0    6   8  10   0   0
11   PCT  GWG   G   A   G   A
12  17.0    3  11  15   0   0
13   9.0    4  14  23   0   0
14  17.8    0   5  20   0   0
15  16.0    6  13  12   0   0
16  14.3    6   8   9   0   0
17  12.9    0   7  19   2   0
18  14.2    5  19  12   0   0
19  13.2    4   9  17   0   0
20  13.1    6   3  10   0   2
21  13.8    8   6   6   4   1
23   PCT  GWG   G   A   G   A
24  12.3   10   7   4   3   2
25  10.3    4   6  18   2   0
26  14.6    7   6  11   2   1
27   7.2    3   6  24   0   0
28   7.5    3   4  24   0   0
29  15.8    5   8  16   0   0
30  12.2    0   4  18   0   0
31  14.7    2   2  13   0   0
32  14.5    5   6  16   0   0
33  16.6    6   5   8   1   0
35   PCT  GWG   G   A   G   A
36  10.8    5   8  16   0   0
37  11.2    6   4  12   1   0
38  14.4    4   8  13   0   0
39  11.9    4   6  18   0   0
40  11.6    7  12  11   0   0
41  15.2    4   8   8   0   2
42  11.0    6   6  13   0   0
43  13.1    2   6  15   0   0
44  11.5    5   3   8   1   1
45  12.7    3  11   5   0   0

In [33]:
# TODO: At this point, look through your dataset by printing
# it. There probably still are some erroneous rows in there.
# What indexing command(s) can you use to select all rows
# EXCEPT those rows?
#
# .. your code here ..
df = df[df['RK']!='RK']
print(df)

     RK                  PLAYER TEAM  GP   G   A PTS  +/- PIM PTS/G  SOG  \
0     1          Jamie Benn, LW  DAL  82  35  52  87    1  64  1.06  253
1     2         John Tavares, C  NYI  82  38  48  86    5  46  1.05  278
2     3        Sidney Crosby, C  PIT  77  28  56  84    5  47  1.09  237
3     4       Alex Ovechkin, LW  WSH  81  53  28  81   10  58  1.00  395
4   NaN       Jakub Voracek, RW  PHI  82  22  59  81    1  78  0.99  221
5     6    Nicklas Backstrom, C  WSH  82  18  60  78    5  40  0.95  153
6     7         Tyler Seguin, C  DAL  71  37  40  77   -1  20  1.08  280
7     8         Jiri Hudler, LW  CGY  78  31  45  76   17  14  0.97  158
8   NaN        Daniel Sedin, LW  VAN  82  20  56  76    5  18  0.93  226
9    10  Vladimir Tarasenko, RW  STL  77  37  36  73   27  31  0.95  264
12  NaN        Nick Foligno, LW  CBJ  79  31  42  73   16  50  0.92  182
13  NaN        Claude Giroux, C  PHI  81  25  48  73   -3  36  0.90  279
14  NaN         Henrik Sedin, C  VAN  82  18  55  73   11  22  0.89  101
15   14       Steven Stamkos, C   TB  82  43  29  72    2  49  0.88  268
16  NaN        Tyler Johnson, C   TB  77  29  43  72   33  24  0.94  203
17   16        Ryan Johansen, C  CBJ  82  26  45  71   -6  40  0.87  202
18   17         Joe Pavelski, C   SJ  82  37  33  70   12  29  0.85  261
19  NaN        Evgeni Malkin, C  PIT  69  28  42  70   -2  60  1.01  212
20  NaN         Ryan Getzlaf, C  ANA  77  25  45  70   15  62  0.91  191
21   20           Rick Nash, LW  NYR  79  42  27  69   29  36  0.87  304
24   21      Max Pacioretty, LW  MTL  80  37  30  67   38  32  0.84  302
25  NaN        Logan Couture, C   SJ  82  27  40  67   -6  12  0.82  263
26   23       Jonathan Toews, C  CHI  81  28  38  66   30  36  0.81  192
27  NaN        Erik Karlsson, D  OTT  82  21  45  66    7  42  0.80  292
28  NaN   Henrik Zetterberg, LW  DET  77  17  49  66   -6  32  0.86  227
29   26        Pavel Datsyuk, C  DET  63  26  39  65   12   8  1.03  165
30  NaN         Joe Thornton, C   SJ  78  16  49  65   -4  30  0.83  131
31   28     Nikita Kucherov, RW   TB  82  28  36  64   38  37  0.78  190
32  NaN        Patrick Kane, RW  CHI  61  27  37  64   10  10  1.05  186
33  NaN          Mark Stone, RW  OTT  80  26  38  64   21  14  0.80  157
36  NaN     Alexander Steen, LW  STL  74  24  40  64    8  33  0.86  223
37  NaN          Kyle Turris, C  OTT  82  24  40  64    5  36  0.78  215
38  NaN     Johnny Gaudreau, LW  CGY  80  24  40  64   11  14  0.80  167
39  NaN         Anze Kopitar, C   LA  79  16  48  64   -2  10  0.81  134
40   35        Radim Vrbata, RW  VAN  79  31  32  63    6  20  0.80  267
41  NaN      Jaden Schwartz, LW  STL  75  28  35  63   13  16  0.84  184
42  NaN       Filip Forsberg, C  NSH  82  26  37  63   15  24  0.77  237
43  NaN       Jordan Eberle, RW  EDM  81  24  39  63  -16  24  0.78  183
44  NaN        Ondrej Palat, LW   TB  75  16  47  63   31  24  0.84  139
45   40         Zach Parise, LW  MIN  74  33  29  62   21  41  0.84  259

     PCT GWG G.1 A.1 G.2 A.2
0   13.8   6  10  13   2   3
1   13.7   8  13  18   0   1
2   11.8   3  10  21   0   0
3   13.4  11  25   9   0   0
4   10.0   3  11  22   0   0
5   11.8   3   3  30   0   0
6   13.2   5  13  16   0   0
7   19.6   5   6  10   0   0
8    8.9   5   4  21   0   0
9   14.0   6   8  10   0   0
12  17.0   3  11  15   0   0
13   9.0   4  14  23   0   0
14  17.8   0   5  20   0   0
15  16.0   6  13  12   0   0
16  14.3   6   8   9   0   0
17  12.9   0   7  19   2   0
18  14.2   5  19  12   0   0
19  13.2   4   9  17   0   0
20  13.1   6   3  10   0   2
21  13.8   8   6   6   4   1
24  12.3  10   7   4   3   2
25  10.3   4   6  18   2   0
26  14.6   7   6  11   2   1
27   7.2   3   6  24   0   0
28   7.5   3   4  24   0   0
29  15.8   5   8  16   0   0
30  12.2   0   4  18   0   0
31  14.7   2   2  13   0   0
32  14.5   5   6  16   0   0
33  16.6   6   5   8   1   0
36  10.8   5   8  16   0   0
37  11.2   6   4  12   1   0
38  14.4   4   8  13   0   0
39  11.9   4   6  18   0   0
40  11.6   7  12  11   0   0
41  15.2   4   8   8   0   2
42  11.0   6   6  13   0   0
43  13.1   2   6  15   0   0
44  11.5   5   3   8   1   1
45  12.7   3  11   5   0   0

In [34]:
# TODO: Get rid of the 'RK' column
#
# .. your code here ..
df = df.drop('RK', 1)
print(df)

                    PLAYER TEAM  GP   G   A PTS  +/- PIM PTS/G  SOG   PCT GWG  \
0           Jamie Benn, LW  DAL  82  35  52  87    1  64  1.06  253  13.8   6
1          John Tavares, C  NYI  82  38  48  86    5  46  1.05  278  13.7   8
2         Sidney Crosby, C  PIT  77  28  56  84    5  47  1.09  237  11.8   3
3        Alex Ovechkin, LW  WSH  81  53  28  81   10  58  1.00  395  13.4  11
4        Jakub Voracek, RW  PHI  82  22  59  81    1  78  0.99  221  10.0   3
5     Nicklas Backstrom, C  WSH  82  18  60  78    5  40  0.95  153  11.8   3
6          Tyler Seguin, C  DAL  71  37  40  77   -1  20  1.08  280  13.2   5
7          Jiri Hudler, LW  CGY  78  31  45  76   17  14  0.97  158  19.6   5
8         Daniel Sedin, LW  VAN  82  20  56  76    5  18  0.93  226   8.9   5
9   Vladimir Tarasenko, RW  STL  77  37  36  73   27  31  0.95  264  14.0   6
12        Nick Foligno, LW  CBJ  79  31  42  73   16  50  0.92  182  17.0   3
13        Claude Giroux, C  PHI  81  25  48  73   -3  36  0.90  279   9.0   4
14         Henrik Sedin, C  VAN  82  18  55  73   11  22  0.89  101  17.8   0
15       Steven Stamkos, C   TB  82  43  29  72    2  49  0.88  268  16.0   6
16        Tyler Johnson, C   TB  77  29  43  72   33  24  0.94  203  14.3   6
17        Ryan Johansen, C  CBJ  82  26  45  71   -6  40  0.87  202  12.9   0
18         Joe Pavelski, C   SJ  82  37  33  70   12  29  0.85  261  14.2   5
19        Evgeni Malkin, C  PIT  69  28  42  70   -2  60  1.01  212  13.2   4
20         Ryan Getzlaf, C  ANA  77  25  45  70   15  62  0.91  191  13.1   6
21           Rick Nash, LW  NYR  79  42  27  69   29  36  0.87  304  13.8   8
24      Max Pacioretty, LW  MTL  80  37  30  67   38  32  0.84  302  12.3  10
25        Logan Couture, C   SJ  82  27  40  67   -6  12  0.82  263  10.3   4
26       Jonathan Toews, C  CHI  81  28  38  66   30  36  0.81  192  14.6   7
27        Erik Karlsson, D  OTT  82  21  45  66    7  42  0.80  292   7.2   3
28   Henrik Zetterberg, LW  DET  77  17  49  66   -6  32  0.86  227   7.5   3
29        Pavel Datsyuk, C  DET  63  26  39  65   12   8  1.03  165  15.8   5
30         Joe Thornton, C   SJ  78  16  49  65   -4  30  0.83  131  12.2   0
31     Nikita Kucherov, RW   TB  82  28  36  64   38  37  0.78  190  14.7   2
32        Patrick Kane, RW  CHI  61  27  37  64   10  10  1.05  186  14.5   5
33          Mark Stone, RW  OTT  80  26  38  64   21  14  0.80  157  16.6   6
36     Alexander Steen, LW  STL  74  24  40  64    8  33  0.86  223  10.8   5
37          Kyle Turris, C  OTT  82  24  40  64    5  36  0.78  215  11.2   6
38     Johnny Gaudreau, LW  CGY  80  24  40  64   11  14  0.80  167  14.4   4
39         Anze Kopitar, C   LA  79  16  48  64   -2  10  0.81  134  11.9   4
40        Radim Vrbata, RW  VAN  79  31  32  63    6  20  0.80  267  11.6   7
41      Jaden Schwartz, LW  STL  75  28  35  63   13  16  0.84  184  15.2   4
42       Filip Forsberg, C  NSH  82  26  37  63   15  24  0.77  237  11.0   6
43       Jordan Eberle, RW  EDM  81  24  39  63  -16  24  0.78  183  13.1   2
44        Ondrej Palat, LW   TB  75  16  47  63   31  24  0.84  139  11.5   5
45         Zach Parise, LW  MIN  74  33  29  62   21  41  0.84  259  12.7   3

   G.1 A.1 G.2 A.2
0   10  13   2   3
1   13  18   0   1
2   10  21   0   0
3   25   9   0   0
4   11  22   0   0
5    3  30   0   0
6   13  16   0   0
7    6  10   0   0
8    4  21   0   0
9    8  10   0   0
12  11  15   0   0
13  14  23   0   0
14   5  20   0   0
15  13  12   0   0
16   8   9   0   0
17   7  19   2   0
18  19  12   0   0
19   9  17   0   0
20   3  10   0   2
21   6   6   4   1
24   7   4   3   2
25   6  18   2   0
26   6  11   2   1
27   6  24   0   0
28   4  24   0   0
29   8  16   0   0
30   4  18   0   0
31   2  13   0   0
32   6  16   0   0
33   5   8   1   0
36   8  16   0   0
37   4  12   1   0
38   8  13   0   0
39   6  18   0   0
40  12  11   0   0
41   8   8   0   2
42   6  13   0   0
43   6  15   0   0
44   3   8   1   1
45  11   5   0   0

In [35]:
# TODO: Ensure there are no holes in your index by resetting
# it. By the way, don't store the original index
#
# .. your code here ..
df = df.reset_index()

In [36]:
# TODO: Check the data type of all columns, and ensure those
# that should be numeric are numeric
print(df.dtypes)
print(df)
print(df.describe())
print('\n\n\n')
print(df['PCT'].describe())

# TODO: Your dataframe is now ready! Use the appropriate 
# commands to answer the questions on the course lab page.

index      int64
PLAYER    object
TEAM      object
GP        object
G         object
A         object
PTS       object
+/-       object
PIM       object
PTS/G     object
SOG       object
PCT       object
GWG       object
G.1       object
A.1       object
G.2       object
A.2       object
dtype: object
    index                  PLAYER TEAM  GP   G   A PTS  +/- PIM PTS/G  SOG  \
0       0          Jamie Benn, LW  DAL  82  35  52  87    1  64  1.06  253
1       1         John Tavares, C  NYI  82  38  48  86    5  46  1.05  278
2       2        Sidney Crosby, C  PIT  77  28  56  84    5  47  1.09  237
3       3       Alex Ovechkin, LW  WSH  81  53  28  81   10  58  1.00  395
4       4       Jakub Voracek, RW  PHI  82  22  59  81    1  78  0.99  221
5       5    Nicklas Backstrom, C  WSH  82  18  60  78    5  40  0.95  153
6       6         Tyler Seguin, C  DAL  71  37  40  77   -1  20  1.08  280
7       7         Jiri Hudler, LW  CGY  78  31  45  76   17  14  0.97  158
8       8        Daniel Sedin, LW  VAN  82  20  56  76    5  18  0.93  226
9       9  Vladimir Tarasenko, RW  STL  77  37  36  73   27  31  0.95  264
10     12        Nick Foligno, LW  CBJ  79  31  42  73   16  50  0.92  182
11     13        Claude Giroux, C  PHI  81  25  48  73   -3  36  0.90  279
12     14         Henrik Sedin, C  VAN  82  18  55  73   11  22  0.89  101
13     15       Steven Stamkos, C   TB  82  43  29  72    2  49  0.88  268
14     16        Tyler Johnson, C   TB  77  29  43  72   33  24  0.94  203
15     17        Ryan Johansen, C  CBJ  82  26  45  71   -6  40  0.87  202
16     18         Joe Pavelski, C   SJ  82  37  33  70   12  29  0.85  261
17     19        Evgeni Malkin, C  PIT  69  28  42  70   -2  60  1.01  212
18     20         Ryan Getzlaf, C  ANA  77  25  45  70   15  62  0.91  191
19     21           Rick Nash, LW  NYR  79  42  27  69   29  36  0.87  304
20     24      Max Pacioretty, LW  MTL  80  37  30  67   38  32  0.84  302
21     25        Logan Couture, C   SJ  82  27  40  67   -6  12  0.82  263
22     26       Jonathan Toews, C  CHI  81  28  38  66   30  36  0.81  192
23     27        Erik Karlsson, D  OTT  82  21  45  66    7  42  0.80  292
24     28   Henrik Zetterberg, LW  DET  77  17  49  66   -6  32  0.86  227
25     29        Pavel Datsyuk, C  DET  63  26  39  65   12   8  1.03  165
26     30         Joe Thornton, C   SJ  78  16  49  65   -4  30  0.83  131
27     31     Nikita Kucherov, RW   TB  82  28  36  64   38  37  0.78  190
28     32        Patrick Kane, RW  CHI  61  27  37  64   10  10  1.05  186
29     33          Mark Stone, RW  OTT  80  26  38  64   21  14  0.80  157
30     36     Alexander Steen, LW  STL  74  24  40  64    8  33  0.86  223
31     37          Kyle Turris, C  OTT  82  24  40  64    5  36  0.78  215
32     38     Johnny Gaudreau, LW  CGY  80  24  40  64   11  14  0.80  167
33     39         Anze Kopitar, C   LA  79  16  48  64   -2  10  0.81  134
34     40        Radim Vrbata, RW  VAN  79  31  32  63    6  20  0.80  267
35     41      Jaden Schwartz, LW  STL  75  28  35  63   13  16  0.84  184
36     42       Filip Forsberg, C  NSH  82  26  37  63   15  24  0.77  237
37     43       Jordan Eberle, RW  EDM  81  24  39  63  -16  24  0.78  183
38     44        Ondrej Palat, LW   TB  75  16  47  63   31  24  0.84  139
39     45         Zach Parise, LW  MIN  74  33  29  62   21  41  0.84  259

     PCT GWG G.1 A.1 G.2 A.2
0   13.8   6  10  13   2   3
1   13.7   8  13  18   0   1
2   11.8   3  10  21   0   0
3   13.4  11  25   9   0   0
4   10.0   3  11  22   0   0
5   11.8   3   3  30   0   0
6   13.2   5  13  16   0   0
7   19.6   5   6  10   0   0
8    8.9   5   4  21   0   0
9   14.0   6   8  10   0   0
10  17.0   3  11  15   0   0
11   9.0   4  14  23   0   0
12  17.8   0   5  20   0   0
13  16.0   6  13  12   0   0
14  14.3   6   8   9   0   0
15  12.9   0   7  19   2   0
16  14.2   5  19  12   0   0
17  13.2   4   9  17   0   0
18  13.1   6   3  10   0   2
19  13.8   8   6   6   4   1
20  12.3  10   7   4   3   2
21  10.3   4   6  18   2   0
22  14.6   7   6  11   2   1
23   7.2   3   6  24   0   0
24   7.5   3   4  24   0   0
25  15.8   5   8  16   0   0
26  12.2   0   4  18   0   0
27  14.7   2   2  13   0   0
28  14.5   5   6  16   0   0
29  16.6   6   5   8   1   0
30  10.8   5   8  16   0   0
31  11.2   6   4  12   1   0
32  14.4   4   8  13   0   0
33  11.9   4   6  18   0   0
34  11.6   7  12  11   0   0
35  15.2   4   8   8   0   2
36  11.0   6   6  13   0   0
37  13.1   2   6  15   0   0
38  11.5   5   3   8   1   1
39  12.7   3  11   5   0   0
           index
count  40.000000
mean   22.500000
std    13.895212
min     0.000000
25%    11.250000
50%    22.500000
75%    33.750000
max    45.000000




count       40
unique      36
top       11.8
freq         2
Name: PCT, dtype: object

In [30]:
df.PCT = pd.to_numeric(df.PCT, errors='coerce')
print(df)
print('\n\n')
print(df.describe())

    index                  PLAYER TEAM  GP   G   A PTS  +/- PIM PTS/G  SOG  \
0       0          Jamie Benn, LW  DAL  82  35  52  87    1  64  1.06  253
1       1         John Tavares, C  NYI  82  38  48  86    5  46  1.05  278
2       2        Sidney Crosby, C  PIT  77  28  56  84    5  47  1.09  237
3       3       Alex Ovechkin, LW  WSH  81  53  28  81   10  58  1.00  395
4       4       Jakub Voracek, RW  PHI  82  22  59  81    1  78  0.99  221
5       5    Nicklas Backstrom, C  WSH  82  18  60  78    5  40  0.95  153
6       6         Tyler Seguin, C  DAL  71  37  40  77   -1  20  1.08  280
7       7         Jiri Hudler, LW  CGY  78  31  45  76   17  14  0.97  158
8       8        Daniel Sedin, LW  VAN  82  20  56  76    5  18  0.93  226
9       9  Vladimir Tarasenko, RW  STL  77  37  36  73   27  31  0.95  264
10     12        Nick Foligno, LW  CBJ  79  31  42  73   16  50  0.92  182
11     13        Claude Giroux, C  PHI  81  25  48  73   -3  36  0.90  279
12     14         Henrik Sedin, C  VAN  82  18  55  73   11  22  0.89  101
13     15       Steven Stamkos, C   TB  82  43  29  72    2  49  0.88  268
14     16        Tyler Johnson, C   TB  77  29  43  72   33  24  0.94  203
15     17        Ryan Johansen, C  CBJ  82  26  45  71   -6  40  0.87  202
16     18         Joe Pavelski, C   SJ  82  37  33  70   12  29  0.85  261
17     19        Evgeni Malkin, C  PIT  69  28  42  70   -2  60  1.01  212
18     20         Ryan Getzlaf, C  ANA  77  25  45  70   15  62  0.91  191
19     21           Rick Nash, LW  NYR  79  42  27  69   29  36  0.87  304
20     24      Max Pacioretty, LW  MTL  80  37  30  67   38  32  0.84  302
21     25        Logan Couture, C   SJ  82  27  40  67   -6  12  0.82  263
22     26       Jonathan Toews, C  CHI  81  28  38  66   30  36  0.81  192
23     27        Erik Karlsson, D  OTT  82  21  45  66    7  42  0.80  292
24     28   Henrik Zetterberg, LW  DET  77  17  49  66   -6  32  0.86  227
25     29        Pavel Datsyuk, C  DET  63  26  39  65   12   8  1.03  165
26     30         Joe Thornton, C   SJ  78  16  49  65   -4  30  0.83  131
27     31     Nikita Kucherov, RW   TB  82  28  36  64   38  37  0.78  190
28     32        Patrick Kane, RW  CHI  61  27  37  64   10  10  1.05  186
29     33          Mark Stone, RW  OTT  80  26  38  64   21  14  0.80  157
30     36     Alexander Steen, LW  STL  74  24  40  64    8  33  0.86  223
31     37          Kyle Turris, C  OTT  82  24  40  64    5  36  0.78  215
32     38     Johnny Gaudreau, LW  CGY  80  24  40  64   11  14  0.80  167
33     39         Anze Kopitar, C   LA  79  16  48  64   -2  10  0.81  134
34     40        Radim Vrbata, RW  VAN  79  31  32  63    6  20  0.80  267
35     41      Jaden Schwartz, LW  STL  75  28  35  63   13  16  0.84  184
36     42       Filip Forsberg, C  NSH  82  26  37  63   15  24  0.77  237
37     43       Jordan Eberle, RW  EDM  81  24  39  63  -16  24  0.78  183
38     44        Ondrej Palat, LW   TB  75  16  47  63   31  24  0.84  139
39     45         Zach Parise, LW  MIN  74  33  29  62   21  41  0.84  259

     PCT GWG G.1 A.1 G.2 A.2
0   13.8   6  10  13   2   3
1   13.7   8  13  18   0   1
2   11.8   3  10  21   0   0
3   13.4  11  25   9   0   0
4   10.0   3  11  22   0   0
5   11.8   3   3  30   0   0
6   13.2   5  13  16   0   0
7   19.6   5   6  10   0   0
8    8.9   5   4  21   0   0
9   14.0   6   8  10   0   0
10  17.0   3  11  15   0   0
11   9.0   4  14  23   0   0
12  17.8   0   5  20   0   0
13  16.0   6  13  12   0   0
14  14.3   6   8   9   0   0
15  12.9   0   7  19   2   0
16  14.2   5  19  12   0   0
17  13.2   4   9  17   0   0
18  13.1   6   3  10   0   2
19  13.8   8   6   6   4   1
20  12.3  10   7   4   3   2
21  10.3   4   6  18   2   0
22  14.6   7   6  11   2   1
23   7.2   3   6  24   0   0
24   7.5   3   4  24   0   0
25  15.8   5   8  16   0   0
26  12.2   0   4  18   0   0
27  14.7   2   2  13   0   0
28  14.5   5   6  16   0   0
29  16.6   6   5   8   1   0
30  10.8   5   8  16   0   0
31  11.2   6   4  12   1   0
32  14.4   4   8  13   0   0
33  11.9   4   6  18   0   0
34  11.6   7  12  11   0   0
35  15.2   4   8   8   0   2
36  11.0   6   6  13   0   0
37  13.1   2   6  15   0   0
38  11.5   5   3   8   1   1
39  12.7   3  11   5   0   0



           index         GP        PCT
count  40.000000  40.000000  40.000000
mean   22.500000  78.275000  13.015000
std    13.895212   4.992238   2.619703
min     0.000000  61.000000   7.200000
25%    11.250000  77.000000  11.575000
50%    22.500000  80.000000  13.150000
75%    33.750000  82.000000  14.425000
max    45.000000  82.000000  19.600000

## HW 5

In [37]:
import pandas as pd
import numpy as np


#
# TODO:
# Load up the dataset, setting correct header labels.
#
# .. your code here ..
columns=['education', 'age', 'capital-gain', 'race', 'capital-loss', 'hours-per-week', 'sex', 'classification']

df = pd.read_csv('datasets/census.data', names=columns)

#
# TODO:
# Use basic pandas commands to look through the dataset... get a
# feel for it before proceeding! Do the data-types of each column
# reflect the values you see when you look through the data using
# a text editor / spread sheet program? If you see 'object' where
# you expect to see 'int32' / 'float64', that is a good indicator
# that there is probably a string or missing value in a column.
# use `your_data_frame['your_column'].unique()` to see the unique
# values of each column and identify the rogue values. If these
# should be represented as nans, you can convert them using
# na_values when loading the dataframe.
#
# .. your code here ..
print(df.head(5))
print(df.dtypes)

   education  age capital-gain   race  capital-loss  hours-per-week     sex  \
0  Bachelors   39         2174  White             0              40    Male
1  Bachelors   50            ?  White             0              13    Male
2    HS-grad   38            ?  White             0              40    Male
3       11th   53            ?  Black             0              40    Male
4  Bachelors   28            0  Black             0              40  Female

  classification
0          <=50K
1          <=50K
2          <=50K
3          <=50K
4          <=50K
education         object
age                int64
capital-gain      object
race              object
capital-loss       int64
hours-per-week     int64
sex               object
classification    object
dtype: object

In [38]:
print(df.describe())
print('\n\n\n')

print(df)

                age  capital-loss  hours-per-week
count  29536.000000  29536.000000    29536.000000
mean      38.506094     84.957408       40.243872
std       13.811739    397.107750       12.326211
min       17.000000      0.000000        1.000000
25%       27.000000      0.000000       40.000000
50%       37.000000      0.000000       40.000000
75%       48.000000      0.000000       45.000000
max       90.000000   4356.000000       99.000000




          education  age capital-gain                race  capital-loss  \
0         Bachelors   39         2174               White             0
1         Bachelors   50            ?               White             0
2           HS-grad   38            ?               White             0
3              11th   53            ?               Black             0
4         Bachelors   28            0               Black             0
5           Masters   37            0               White             0
6               9th   49            0               Black             0
7           HS-grad   52            0               White             0
8           Masters   31        14084               White             0
9         Bachelors   42         5178               White             0
10     Some-college   37            0               Black             0
11        Bachelors   30            0  Asian-Pac-Islander             0
12        Bachelors   23            0               White             0
13          7th-8th   34            0  Amer-Indian-Eskimo             0
14          HS-grad   25            0               White             0
15          HS-grad   32            0               White             0
16             11th   38            0               White             0
17          Masters   43            0               White             0
18        Doctorate   40            0               White             0
19          HS-grad   54            0               Black             0
20              9th   35            0               Black             0
21             11th   43            0               White          2042
22          HS-grad   59            0               White             0
23        Bachelors   56            0               White             0
24          HS-grad   19            0               White             0
25     Some-college   54            0  Asian-Pac-Islander             0
26          HS-grad   39            0               White             0
27          HS-grad   49            0               White             0
28     Some-college   20            0               Black             0
29        Bachelors   45            0               White          1408
...             ...  ...          ...                 ...           ...
29506       HS-grad   30            0               White             0
29507          10th   32            0               White             0
29508  Some-college   22            0               White             0
29509       HS-grad   31            0               White             0
29510       HS-grad   29            0               White             0
29511     Bachelors   35            0               White             0
29512     Bachelors   30            0  Asian-Pac-Islander             0
29513     Doctorate   34            0               White             0
29514     Bachelors   54            0  Asian-Pac-Islander             0
29515  Some-college   37            0               White             0
29516          12th   22            0               Black             0
29517     Bachelors   34            0               White             0
29518       HS-grad   30            0               Black             0
29519     Bachelors   38        15020               Black             0
29520     Doctorate   71            0               White             0
29521       HS-grad   45            0               White             0
29522       HS-grad   41            0               Black             0
29523       HS-grad   72            0               White             0
29524       Masters   31            0               Other             0
29525       HS-grad   43            0               White             0
29526  Some-college   43            0               White             0
29527  Some-college   43            0               White             0
29528          10th   32            0  Amer-Indian-Eskimo             0
29529       Masters   32            0  Asian-Pac-Islander             0
29530       Masters   53            0               White             0
29531  Some-college   22            0               White             0
29532       HS-grad   40            0               White             0
29533       HS-grad   58            0               White             0
29534       HS-grad   22            0               White             0
29535       HS-grad   52        15024               White             0

       hours-per-week     sex classification
0                  40    Male          <=50K
1                  13    Male          <=50K
2                  40    Male          <=50K
3                  40    Male          <=50K
4                  40  Female          <=50K
5                  40  Female          <=50K
6                  16  Female          <=50K
7                  45    Male           >50K
8                  50  Female           >50K
9                  40    Male           >50K
10                 80    Male           >50K
11                 40    Male           >50K
12                 30  Female          <=50K
13                 45    Male          <=50K
14                 35    Male          <=50K
15                 40    Male          <=50K
16                 50    Male          <=50K
17                 45  Female           >50K
18                 60    Male           >50K
19                 20  Female          <=50K
20                 40    Male          <=50K
21                 40    Male          <=50K
22                 40  Female          <=50K
23                 40    Male           >50K
24                 40    Male          <=50K
25                 60    Male           >50K
26                 80    Male          <=50K
27                 40    Male          <=50K
28                 44    Male          <=50K
29                 40    Male          <=50K
...               ...     ...            ...
29506              55    Male          <=50K
29507              40    Male          <=50K
29508              40    Male          <=50K
29509              40  Female          <=50K
29510              35  Female          <=50K
29511              55  Female           >50K
29512              99  Female          <=50K
29513              60    Male           >50K
29514              50    Male           >50K
29515              39  Female          <=50K
29516              35    Male          <=50K
29517              55  Female           >50K
29518              46    Male          <=50K
29519              45  Female           >50K
29520              10    Male           >50K
29521              40  Female          <=50K
29522              32  Female          <=50K
29523              25    Male          <=50K
29524              30  Female          <=50K
29525              40    Male          <=50K
29526              40  Female          <=50K
29527              50    Male          <=50K
29528              40    Male          <=50K
29529              11    Male          <=50K
29530              40    Male           >50K
29531              40    Male          <=50K
29532              40    Male           >50K
29533              40  Female          <=50K
29534              20    Male          <=50K
29535              40  Female           >50K

[29536 rows x 8 columns]

In [ ]:

#
# TODO:
# Look through your data and identify any potential categorical
# features. Ensure you properly encode any ordinal and nominal
# types using the methods discussed in the chapter.
#
# Be careful! Some features can be represented as either categorical
# or continuous (numerical). Think to yourself, does it generally
# make more sense to have a numeric type or a series of categories
# for these somewhat ambigious features?
#
# .. your code here ..



#
# TODO:
# Print out your dataframe
#
# .. your code here ..